//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Elmish Land (v1.0.0-alpha.87).
// Here are the available commands:
// 
// dotnet elmish-land init ...... create a new project in the current directory
// dotnet elmish-land upgrade ....... upgrade project to the latest elmish-land
// dotnet elmish-land server ........................... run a local dev server
// dotnet elmish-land build ..................... build your app for production
// dotnet elmish-land add page <url> ........................... add a new page
// dotnet elmish-land add layout <name> ...................... add a new layout
// dotnet elmish-land routes ...................... list all routes in your app
// 
// Want to learn more? Visit https://elmish.land
// 
// This file will be overwritten when re-executing
// 'dotnet elmish-land server' or 'dotnet elmish-land build'.
// </auto-generated>
//------------------------------------------------------------------------------
module ``elmish-land``.App

open Elmish
open Elmish.React
open Elmish.HMR
open Feliz
open Feliz.Router
open ``elmish-land``.Routes
open ``elmish-land``.Pages

[<RequireQualifiedAccess>]
type Page =
    | ``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` of elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.Model
    | Testy of elmish-land.Pages.Testy.Page.Model
    | NotFound

type Model = {
    Shared: Shared.Model
    CurrentRoute: Route
    CurrentPage: Page
}

type Msg =
| SharedMsg of Shared.Msg
| RouteChanged of Route
| ``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg`` of elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.Msg
| TestyMsg of elmish-land.Pages.Testy.Page.Msg

let init () =
    let initialUrl = Route.parse (Router.currentUrl ())
    let sharedModel, sharedCmd = Shared.init ()

    let defaultModel = {
        Shared = sharedModel
        CurrentRoute = initialUrl
        CurrentPage = Page.NotFound
    }

    let initPage init initArgs page msg =
        let nextModel, nextCmd = init initArgs
        let nextPage = page nextModel

        {
            defaultModel with
                CurrentPage = nextPage
        },
        Cmd.batch [ sharedCmd; Cmd.map msg nextCmd ]

    match initialUrl with
    | Route.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` ->
        initPage elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.init () Page.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` ``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg``
    | Route.Testy ->
        initPage elmish-land.Pages.Testy.Page.init () Page.Testy TestyMsg
    | Route.NotFound ->
        {
            defaultModel with
                CurrentPage = Page.NotFound
        },
        Cmd.none

let update (msg: Msg) (model: Model) =
    let updatePage update msg' model' page msg =
        let model'', cmd = update msg' model'

        {
            model with
                CurrentPage = page model''
        },
        Cmd.map msg cmd
    match msg, model.CurrentPage with
    | SharedMsg msg', _ ->
        let model'', cmd = Shared.update msg' model.Shared
        { model with Shared = model'' }, Cmd.map SharedMsg cmd
    | RouteChanged nextRoute, _ ->
        let changeRoute init initArgs page msg =
            let model', msg' = init initArgs
            {
                model with
                    CurrentPage = page model'
                    CurrentRoute = nextRoute
            },
            Cmd.map msg msg'
        match nextRoute with
        | Route.``:_Projects_Elmish-land_MyProject_Src_Pages_Home``  ->
            changeRoute elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.init () Page.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` ``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg``
        | Route.Testy  ->
            changeRoute elmish-land.Pages.Testy.Page.init () Page.Testy TestyMsg
        | Route.NotFound ->
            {
                model with
                    CurrentPage = Page.NotFound
                    CurrentRoute = Route.NotFound
            },
            Cmd.none
    | ``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg`` msg', Page.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` model' ->
        updatePage elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.update msg' model' Page.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` ``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg``
    | TestyMsg msg', Page.Testy model' ->
        updatePage elmish-land.Pages.Testy.Page.update msg' model' Page.Testy TestyMsg
    | msg', model' ->
        printfn $"Unhandled App.Msg and CurrentPage.Model. Got\nMsg:\n%A{msg'}\nCurrentPage.Model:\n%A{model'}"
        model, Cmd.none

let view (model: Model) (dispatch: Msg -> unit) =
    let currentPageView =
        match model.CurrentPage with
        | Page.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` m -> elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.view m (``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg`` >> dispatch)
        | Page.Testy m -> elmish-land.Pages.Testy.Page.view m (TestyMsg >> dispatch)
        | Page.NotFound -> Html.h1 "Page not found"

    React.router [
        router.onUrlChanged (Route.parse >> RouteChanged >> dispatch)
        router.children [ currentPageView ]
    ]

let subscribe model =
    Sub.batch [
        Sub.map "Shared_App" SharedMsg [ Shared.subscribeShared id ]
        match model.CurrentPage with
        | Page.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` m -> Sub.map "``:_Projects_Elmish-land_MyProject_Src_Pages_Home``" ``:_Projects_Elmish-land_MyProject_Src_Pages_HomeMsg`` (elmish-land.Pages.``:``.Projects.``Elmish-land``.MyProject.Src.Pages.Home.Page.subscribe m)
        | Page.Testy m -> Sub.map "Testy" TestyMsg (elmish-land.Pages.Testy.Page.subscribe m)
        | Page.NotFound -> Sub.none
    ]

Program.mkProgram init update view
|> Program.withErrorHandler (fun (msg, ex) -> printfn "Program error handler:\r\n%s\r\n%O" msg ex)
|> Program.withReactBatched "app"
|> Program.withSubscription subscribe
|> Program.run
