//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Elmish Land (v1.0.0-alpha.87).
// Here are the available commands:
//
// dotnet elmish-land init ...... create a new project in the current directory
// dotnet elmish-land upgrade ....... upgrade project to the latest elmish-land
// dotnet elmish-land server ........................... run a local dev server
// dotnet elmish-land build ..................... build your app for production
// dotnet elmish-land add page <url> ........................... add a new page
// dotnet elmish-land add layout <name> ...................... add a new layout
// dotnet elmish-land routes ...................... list all routes in your app
//
// Want to learn more? Visit https://elmish.land
//
// This file will be overwritten when re-executing
// 'dotnet elmish-land server' or 'dotnet elmish-land build'.
// </auto-generated>
//------------------------------------------------------------------------------
module ``elmish-land``.Routes

open Feliz.Router

[<RequireQualifiedAccess>]
type Route =
    | ``:_Projects_Elmish-land_MyProject_Src_Pages_Home``
    | Testy
    | NotFound

module Route =
    let asUrl =
        function
        | Route.``:_Projects_Elmish-land_MyProject_Src_Pages_Home`` ->
            $"#C:/Projects/elmish-land/MyProject/src/Pages/Home"
        | Route.Testy -> $"#/Testy"
        | Route.NotFound -> "notFound"

    let parse (xs: string list) =
        match xs |> List.map (fun x -> x.ToLowerInvariant()) with
        | [ "c:"; "projects"; "elmish-land"; "myproject"; "src"; "pages"; "home" ]
        | [ "c:"; "projects"; "elmish-land"; "myproject"; "src"; "pages"; "home"; Route.Query _ ] ->
            Route.``:_Projects_Elmish-land_MyProject_Src_Pages_Home``
        | [ "testy" ]
        | [ "testy"; Route.Query _ ] -> Route.Testy
        | other ->
            printfn "Route not found: '%A'" other
            Route.NotFound
